import 'package:example/page_util.dart';
import 'package:flutter/material.dart';
import 'package:tdesign/tdesign.dart';

class IconsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ExamplePage(child: _body(context), title: 'Icon');
  }

  Widget _body(BuildContext context) {
    return ListView(children: [
      PageUtil.buildSubTitle("将IconData传入Icon构造器配置和使用"),
      _useOfIcons(context),
      PageUtil.buildSubTitle("全部Icon"),
      PageUtil.buildTile(context, _showIconsInGrid(_iconListAll), height: null),
    ]);
  }

  final _iconListAll = [
    TDIcons.add,
    TDIcons.addCircle,
    TDIcons.addRectangle,
    TDIcons.app,
    TDIcons.arrowDown,
    TDIcons.arrowDownRectangle,
    TDIcons.arrowDown,
    TDIcons.arrowLeft,
    TDIcons.arrowRight,
    TDIcons.arrowUp,
    TDIcons.attach,
    TDIcons.backtopRectangle,
    TDIcons.backtop,
    TDIcons.backward,
    TDIcons.barcode,
    TDIcons.books,
    TDIcons.browseOff,
    TDIcons.browse,
    TDIcons.bulletpoint,
    TDIcons.calendar,
    TDIcons.call,
    TDIcons.caretDown,
    TDIcons.caretLeft,
    TDIcons.caretRight,
    TDIcons.caretUp,
    TDIcons.cart,
    TDIcons.chartBar,
    TDIcons.chartBubble,
    TDIcons.chartPie,
    TDIcons.chart,
    TDIcons.chat,
    TDIcons.checkCircleFilled,
    TDIcons.checkCircle,
    TDIcons.checkRectangle,
    TDIcons.check,
    TDIcons.chevronDownCircle,
    TDIcons.chevronDownRectangle,
    TDIcons.chevronDown,
    TDIcons.chevronLeftCircle,
    TDIcons.chevronLeftRectangle,
    TDIcons.chevronLeftDouble,
    TDIcons.chevronLeft,
    TDIcons.chevronRightCircle,
    TDIcons.chevronRightRectangle,
    TDIcons.chevronRightDouble,
    TDIcons.chevronRight,
    TDIcons.chevronUpCircle,
    TDIcons.chevronUpRectangle,
    TDIcons.chevronUp,
    TDIcons.closeCircleFilled,
    TDIcons.closeCircle,
    TDIcons.closeRectangle,
    TDIcons.close,
    TDIcons.cloudDownload,
    TDIcons.cloudUpload,
    TDIcons.cloud,
    TDIcons.code,
    TDIcons.creditcard,
    TDIcons.cursor,
    TDIcons.delete,
    TDIcons.desktop,
    TDIcons.discountFilled,
    TDIcons.discount,
    TDIcons.download,
    TDIcons.edit,
    TDIcons.ellipsis,
    TDIcons.enter,
    TDIcons.errorCircleFilled,
    TDIcons.errorCircle,
    TDIcons.fileAdd,
    TDIcons.fileCopy,
    TDIcons.fileExcel,
    TDIcons.fileImage,
    TDIcons.filePaste,
    TDIcons.filePdf,
    TDIcons.filePowerpoint,
    TDIcons.fileUnknown,
    TDIcons.fileWord,
    TDIcons.file,
    TDIcons.filter,
    TDIcons.flag,
    TDIcons.folderAdd,
    TDIcons.folderOpen,
    TDIcons.folder,
    TDIcons.fork,
    TDIcons.formatHorizontalAlignBottom,
    TDIcons.formatHorizontalAlignCenter,
    TDIcons.formatHorizontalAlignTop,
    TDIcons.formatVerticalAlignCenter,
    TDIcons.formatVerticalAlignLeft,
    TDIcons.formatVerticalAlignRight,
    TDIcons.forward,
    TDIcons.fullscreenExit,
    TDIcons.fullsreen,
    TDIcons.genderFemale,
    TDIcons.genderMale,
    TDIcons.gift,
    TDIcons.heartFilled,
    TDIcons.heart,
    TDIcons.helpCircleFilled,
    TDIcons.helpCircle,
    TDIcons.help,
    TDIcons.history,
    TDIcons.home,
    TDIcons.hourglass,
    TDIcons.image,
    TDIcons.infoCircleFilled,
    TDIcons.infoCircle,
    TDIcons.internet,
    TDIcons.jump,
    TDIcons.laptop,
    TDIcons.layers,
    TDIcons.linkUnlink,
    TDIcons.link,
    TDIcons.loadingBlue,
    TDIcons.loadingWhite,
    TDIcons.loading,
    TDIcons.location,
    TDIcons.lockOff,
    TDIcons.lockOn,
    TDIcons.login,
    TDIcons.logoAndroid,
    TDIcons.logoApple,
    TDIcons.logoChrome,
    TDIcons.logoGithub,
    TDIcons.logoIe,
    TDIcons.logoWindows,
    TDIcons.mail,
    TDIcons.menuFold,
    TDIcons.menuUnfold,
    TDIcons.minusCircle,
    TDIcons.minusRectangle,
    TDIcons.mobileVibrate,
    TDIcons.mobile,
    TDIcons.moneyCircle,
    TDIcons.more,
    TDIcons.move,
    TDIcons.next,
    TDIcons.notificationFilled,
    TDIcons.notification,
    TDIcons.orderAdjustmentColumn,
    TDIcons.orderAscending,
    TDIcons.orderDescending,
    TDIcons.pageFirst,
    TDIcons.pageLast,
    TDIcons.photo,
    TDIcons.pin,
    TDIcons.playCircle,
    TDIcons.pointingHand,
    TDIcons.poweroff,
    TDIcons.previous,
    TDIcons.print,
    TDIcons.qrcode,
    TDIcons.queue,
    TDIcons.radioIcon,
    TDIcons.refresh,
    TDIcons.remove,
    TDIcons.rollback,
    TDIcons.save,
    TDIcons.scan,
    TDIcons.search,
    TDIcons.secured,
    TDIcons.server,
    TDIcons.service,
    TDIcons.setting,
    TDIcons.share,
    TDIcons.shop,
    TDIcons.slash,
    TDIcons.sound,
    TDIcons.starFilled,
    TDIcons.star,
    TDIcons.stopCircle,
    TDIcons.stop,
    TDIcons.swapLeft,
    TDIcons.swapRight,
    TDIcons.swap,
    TDIcons.thumbDown,
    TDIcons.thumbUp,
    TDIcons.timeFilled,
    TDIcons.time,
    TDIcons.tips,
    TDIcons.tools,
    TDIcons.unfoldLess,
    TDIcons.unfoldMore,
    TDIcons.upload,
    TDIcons.usb,
    TDIcons.userAdd,
    TDIcons.userAvatar,
    TDIcons.userClear,
    TDIcons.user,
    TDIcons.usergroupAdd,
    TDIcons.usergroupClear,
    TDIcons.usergroup,
    TDIcons.video,
    TDIcons.viewColumn,
    TDIcons.viewList,
    TDIcons.viewModule,
    TDIcons.wallet,
    TDIcons.wifi,
    TDIcons.zoomIn,
    TDIcons.zoomOut
  ];

  Widget _useOfIcons(BuildContext context) {
    return PageUtil.buildTile(
      context,
      Row(
        children: [
          Icon(TDIcons.logoGithub, size: 50),
          _spacer(),
          Icon(TDIcons.logoGithub, color: TDColors.green, size: 40),
          _spacer(),
          Icon(TDIcons.logoGithub, color: TDColors.blue, size: 30),
          _spacer(),
          Icon(TDIcons.link, color: TDColors.red, size: 50),
          _spacer(),
          Icon(TDIcons.link, color: TDColors.orange, size: 40),
          _spacer(),
          Icon(TDIcons.link, size: 30),
        ],
      ),
    );
  }

  Widget _spacer() {
    return SizedBox(width: 10);
  }

  Widget _showIconsInGrid(List<IconData> list) {
    return Padding(
      padding: EdgeInsets.symmetric(vertical: 15),
      child: GridView.builder(
        shrinkWrap: true,
        itemCount: list.length,
        physics: NeverScrollableScrollPhysics(),
        padding: EdgeInsets.symmetric(horizontal: 16),
        gridDelegate: SliverGridDelegateWithMaxCrossAxisExtent(
          maxCrossAxisExtent: 20,
          mainAxisSpacing: 20,
          crossAxisSpacing: 20,
          childAspectRatio: 1,
        ),
        itemBuilder: (context, index) {
          return Icon(list[index]);
        },
      ),
    );
  }
}
